spring.datasource.driver-class-name=org.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysqldb://localhost:3306/malldb
spring.datasource.username=malldbuser
spring.datasource.password=malldbuser

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true